name: ci

on:
  push:

jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kaplan2539/p4a-container
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    permissions:
        contents: read
#        packages: write
#        attestations: write
#        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run python-for-android
        run: |
          p4a apk \
            --private src \
            --name hello_kivy \
            --dist_name hello_kivy \
            --package de.deac0.hello_kivy \
            --version 0.1 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy \
            --arch=armeabi-v7a
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: hello_kivy-debug-0.1.apk
