name: ci

on:
  push:

jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kaplan2539/p4a-container
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    permissions:
        contents: read
#        packages: write
#        attestations: write
#        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/python-for-android
            ~/.gradle
          key: p4a-${{ runner.os }}-cache

      - name: Run python-for-android
        run: |
          p4a apk \
            --private src \
            --name hello_kivy \
            --dist_name hello_kivy \
            --package de.deac0.hello_kivy \
            --version 0.1 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy,sounddevice,soundfile,numpy \
            --arch=armeabi-v7a \
            --permissions=RECORD_AUDIO,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
            
      - name: Generate GitHub Pages
        run: |
          mkdir -p pages_out
          rm -rf pages_out/*
          cp hello_kivy-debug-0.1.apk pages_out/
          sudo apt update
          sudo apt install -y qrencode
          echo '<!DOCTYPE html>' >pages_out/index.html
          echo '<html><body><p><pre>' >pages_out/index.html
          echo 'https://d.eadc0.de/hello-kivy/hello_kivy-debug-0.1.apk' | qrencode -o- -t UTF8i >> pages_out/index.html
          echo "</pre></p><p><a href=\"https://d.eadc0.de/hello-kivy/hello_kivy-debug-0.1.apk\">hello_kivy-debug-0.1.apk</a></p>" >> pages_out/index.html
          echo '</body></html>' >>pages_out/index.html

      - name: Archive binary
        id: archive-binary
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: hello_kivy-debug-0.1.apk

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages_out

# Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build-in-docker

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
